import React from "react";
import {useState} from 'react';
import {schedule, saveSchedule} from './api';
import ProcessForm from './components/ProcessForm'; import GanttChart from './components/GanttChart'; import Results from './components/Results'; import Comparison from './components/Comparison'; import History from './components/History';
const initial = {algorithm:'fcfs', time_quantum:2, processes:[{pid:'P1',arrival_time:0,burst_time:5,priority:2},{pid:'P2',arrival_time:1,burst_time:3,priority:1},{pid:'P3',arrival_time:2,burst_time:2,priority:3}]};
const labels = {fcfs:'FCFS',sjf_non_preemptive:'SJF',round_robin:'Round Robin',priority_non_preemptive:'Priority'};
export default function App() {
  const [input,setInput]=useState(initial), [result,setResult]=useState(null), [comparison,setComparison]=useState(null), [loading,setLoading]=useState(false), [error,setError]=useState('');
  const valid = () => input.processes.every(p => Number.isInteger(p.arrival_time) && p.arrival_time >= 0 && Number.isInteger(p.burst_time) && p.burst_time > 0 && (!input.algorithm.startsWith('priority') || Number.isInteger(p.priority))) && (input.algorithm !== 'round_robin' || input.time_quantum > 0);
  const execute = async () => { if(!valid()) {setError('Arrival must be 0+, burst and quantum must be at least 1, and priority must be an integer when required.'); return;} setLoading(true);setError('');try {setResult(await schedule(input));setComparison(null);}catch(e){setError(e.message)}finally{setLoading(false)}};
  const compare = async () => {if(!valid()){setError('Fix the input values before comparing.');return;}setLoading(true);setError('');try {const algorithms=Object.keys(labels);const results=await Promise.all(algorithms.map(algorithm=>schedule({...input,algorithm})));setComparison(results.map((r,i)=>({algorithm:labels[algorithms[i]],waiting:r.aggregate.average_waiting_time})));setResult(null);}catch(e){setError(e.message)}finally{setLoading(false)}};
  const save = async () => {if(!valid()){setError('Fix the input values before saving.');return;}setLoading(true);setError('');try {setResult(await saveSchedule(input));setComparison(null);}catch(e){setError(e.message)}finally{setLoading(false)}};
  const replay = (run) => {setInput({algorithm:run.algorithm,time_quantum:run.time_quantum || 2,processes:run.inputs.processes});setResult({...run.results,algorithm:run.algorithm});setComparison(null);window.scrollTo({top:0,behavior:'smooth'});};
  return <main className="container py-4 py-md-5 app-shell"><header className="hero mb-4 mb-md-5"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/> CPU scheduling lab</div><h1>Make every <em>cycle</em> visible.</h1><p>Compose a workload, simulate CPU execution, and understand the trade-offs in one focused command centre.</p><div className="hero-pills"><span>6 scheduling modes</span><span>Animated timeline</span><span>Live comparison</span></div></div><div className="cpu-orb" aria-hidden="true"><div className="orb-core">CPU<small>ONLINE</small></div><i/><b/><span/></div></header><div className="row g-4"><section className="col-lg-7"><ProcessForm input={input} setInput={setInput} onRun={execute} onCompare={compare} onSave={save} loading={loading}/>{error && <div className="alert alert-danger mt-3">{error}</div>}<div className="mt-4"><History onReplay={replay}/></div></section><section className="col-lg-5">{comparison ? <Comparison data={comparison}/> : <><div className="empty-state mb-3">{!result && <><span>Ready to simulate</span><p>Configure the workload on the left, then run the scheduler to reveal execution metrics.</p></>}</div><Results result={result}/><div className="mt-3"><GanttChart segments={result?.segments}/></div></>}</section></div></main>;
}
